baseURL = 'https://kolmteistov.github.io/'
languageCode = 'en-us'
title = 'Arie Kolmteistov'
theme = "PaperMod"
defaultContentLanguage = "en"
timeZone = "Asia/Jakarta"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10

[[menu.main]]
    name = "Whitepaper"
    url = "/whitepaper.pdf"
    weight = 20

[params]
    ShowBreadCrumbs = true
    ShowPostNavLinks = true
    ShowReadingTime = true
    ShowShareButtons = false
    ShowCodeCopyButtons = true
    DateFormat = "January 2, 2006"
